# travis.yml for https://github.com/giesselmann/STRique

language: python

matrix:
  include:
  # OSX builds
  - os: osx
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
    language: generic
    env: PYTHON=3.5
  - os: osx
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
    language: generic
    env: PYTHON=3.6
  - os: osx
    language: generic
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
    env: PYTHON=3.7
  # Linux builds
  - os: linux
    language: generic
    compiler: gcc
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
          - gfortran-6
          - swig
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.5
  - os: linux
    language: generic
    compiler: gcc
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
          - gfortran-6
          - swig
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.6
  - os: linux
    language: generic
    compiler: gcc
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
          - gfortran-6
          - swig
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7

notifications:
  email: false

install: 
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
    
script: 
  - python scripts/STRique_test.py 
