# travis.yml for https://github.com/giesselmann/STRique
language: python
sudo: true

matrix:
  include:
  # OSX builds
  - os: osx
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
      - PYTHON=3.5
    python: "3.5"
  - os: osx
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
      - PYTHON=3.6
    python: "3.6"
  - os: osx
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
      - PYTHON=3.7
    python: "3.7"
  # Linux builds
  - os: linux
    python: "3.5"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
          - gfortran-6
          - swig
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.5
  - os: linux
    python: "3.6"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
          - gfortran-6
          - swig
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.6
  - os: linux
    dist: xenial
    python: "3.7"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
          - gfortran-6
          - swig
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7

notifications:
  email: false

install:
  - sudo rm /usr/bin/gcc && sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++
  - python --version
  - pip install -r requirements.txt
  - python setup.py install
    
script: 
  - python scripts/STRique_test.py 
