# travis.yml for https://github.com/giesselmann/STRique

language: python

python:
  - "3.5"

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - python setup.py install
    
script: 
  - python scripts/STRique_test.py 