# travis.yml for https://github.com/giesselmann/STRique
language: python
sudo: true

matrix:
  include:
  # Linux builds
  - name: "Python 3.5 Xenial"
    os: linux
    language: python
    python: "3.5"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.5
  - name : "Python 3.6 Xenial"
    os: linux
    language: python
    python: "3.6"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.6
  - name : "Python 3.7 Xenial"
    os: linux
    language: python
    dist: xenial
    python: "3.7"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7
  - name : "Python 3.5 macOS"
    os: osx
    osx_image: xcode10.2
    language: shell


notifications:
  email: false

install:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - alias python=python3
  - python setup.py install

script:
  - alias python=python3
  - python scripts/STRique_test.py
  - python scripts/STRique.py index data/ > data/reads.fofn
  - cat data/c9orf72.sam | python scripts/STRique.py count data/reads.fofn models/r9_4_450bps.model configs/repeat_config.tsv --config configs/STRique.json --mod_model models/r9_4_450bps_mCpG.model --log_level debug
