# travis.yml for https://github.com/giesselmann/STRique
language: python
sudo: true

matrix:
  include:
  # OSX builds
  - os: osx
    language: generic
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
      - PYTHON=3.5.1
  - os: osx
    language: generic
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
      - PYTHON=3.6.0
  - os: osx
    language: generic
    compiler: gcc
    env:
      - CXX_COMPILER='g++'
      - C_COMPILER='gcc'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='Release'
      - PYTHON=3.7.0
  # Linux builds
  - os: linux
    language: python
    python: "3.5"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.5
  - os: linux
    language: python
    python: "3.6"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.6
  - os: linux
    language: python
    dist: xenial
    python: "3.7"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7

notifications:
  email: false
  
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update
        brew install openssl readline
        brew outdated pyenv || brew upgrade pyenv
        brew install pyenv-virtualenv
        pyenv install $PYTHON
        export PYENV_VERSION=$PYTHON
        export PATH="/Users/travis/.pyenv/shims:${PATH}"
        pyenv-virtualenv venv
        source venv/bin/activate
    fi

install:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - python --version
  - pip install -r requirements.txt
  - python setup.py install
    
script: 
  - python scripts/STRique_test.py 
