# travis.yml for https://github.com/giesselmann/STRique

language: python

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.5
  - os: osx
    language: generic
    env: PYTHON=3.6
  - os: osx
    language: generic
    env: PYTHON=3.7
  - os: linux
    language: generic
    env: PYTHON=3.5
  - os: linux
    language: generic
    env: PYTHON=3.6
  - os: linux
    language: generic
    env: PYTHON=3.7

notifications:
  email: false

python:
  - "3.5"

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - python setup.py install
    
script: 
  - python scripts/STRique_test.py 
