# travis.yml for https://github.com/giesselmann/STRique
language: python
sudo: true

matrix:
  include:
  # Linux builds
  - os: linux
    language: python
    python: "3.5"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.5
  - os: linux
    language: python
    python: "3.6"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - cmake3
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.6
  - os: linux
    language: python
    dist: xenial
    python: "3.7"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
    env:
      - CXX_COMPILER='g++-6'
      - C_COMPILER='gcc-6'
      - Fortran_COMPILER='gfortran-6'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7

notifications:
  email: false

install:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - python --version
  - pip install -r requirements.txt
  - python setup.py install
    
script: 
  - python scripts/STRique_test.py 
  - python scripts/STRique.py index data/ > data/reads.fofn
  - cat data/c9orf72.sam | python3 scripts/STRique.py count data/reads.fofn models/r9_4_450bps.model configs/repeat_config.tsv --config configs/STRique.json --mod_model models/r9_4_450bps_mCpG.model --log_level debug
